CREATE TABLE IF NOT EXISTS user (
	id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(200) NOT NULL,
    createAt DATETIME NULL DEFAULT now(),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS board (
	id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    title VARCHAR(100) NOT NULL,
    content VARCHAR(1024) NOT NULL,
    cnt INT NULL DEFAULT 0,
    createAt DATETIME NULL DEFAULT now(),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS product (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    title VARCHAR(100) NOT NULL,
    picture BLOB NULL,
    price INT NOT NULL,
    isbn VARCHAR(100) NULL,
    content VARCHAR(4096) NOT NULL,
    cnt INT NULL DEFAULT 0,
    creatAt DATETIME NULL DEFAULT NOW(),
    PRIMARY KEY (id)
);

